# FROM openjdk:22-jdk
# ADD target/rest-demo.jar  rest-demo.jar
# ENTRYPOINT ["java","-jar","/rest-demo.jar"]
##here we create docker file as well as docker images
## docker build -t sahil/rest-demo:v3 . we are building image